from pytube import YouTube
link = input("Enter the link:")
yt = YouTube(link)
print("Title:",yt.title)
print("Number of Views:",yt.views)
print("Length of the video",yt.length,"seconds")
print("Description:",yt.description)
print("Ratings:",yt.rating)
print(yt.streams.filter(only_audio=True))
ys = yt.streams.get_highest_resolution()
ys = yt.streams.get_by_itag(22)
print("Downloading...")
ys.download()
print("Download Complete.")
